### ISSUE TITLE
add bobsled doge image

### ISSUE THREAD

**Issue by samccone** [samccone/dogesay#14]
something like this
http://www.cbc.ca/strombo/content/images/doge-cool-runnings.jpg

dogesay.com/?image=bobsled

---

doge bounty 500

**Comment by markalfred** [comment]
:+1:

**Comment by samccone** [comment]
![](http://i.imgur.com/NksbGlL.jpg)

**Comment by jescalan** [comment]
Oh yeah that one is way better

**Comment by markalfred** [comment]
![image](https://f.cloud.github.com/assets/3876443/1979774/eb4a3332-83b5-11e3-9f0c-15c9c8474e65.png)

art.
