### ISSUE TITLE
All dogesay.com pages are 502 bad gateway :(

### ISSUE THREAD

**Issue by ghostlandr** [samccone/dogesay#22]
I wanna see what the doge say

**Comment by samccone** [comment]
looks like the server went down :(

ping @jenius :dog:

**Comment by jescalan** [comment]
Ah I'm sorry, let me try to get this up again

**Comment by jescalan** [comment]
All set, sorry bout that guys

**Comment by samccone** [comment]
![](http://dogesay.com/thanks/jeff?image=moon)

**Comment by ghostlandr** [comment]
![image](https://cloud.githubusercontent.com/assets/8973794/8332928/c2060052-1a4d-11e5-91ca-4afb72613316.png)
