### ISSUE TITLE
add dogecoin image option

### ISSUE THREAD

**Issue by kylemac** [samccone/dogesay#8]
After seeing this abomination of comic-sans overlayed on a doge, it feels there should definitely be an alternate dogecoin image option

![](http://i.imgur.com/3eWzb7F.jpg)

**Comment by samccone** [comment]
reward 1000 DogeCoin

**Comment by samccone** [comment]
`?image=dogecoin`

**Comment by jescalan** [comment]
yep, was thinking the same thing. :+1:
