### ISSUE TITLE
Multiple Doge Sayings delimited by '/'

### ISSUE THREAD

**Issue by nathanharper** [samccone/dogesay#9]
I was going to suggest that you should be able to give the doge multiple phrases to say  by extending the path, until I realized it's already implemented but disabled by the slice operation on line 22 of doge.coffee:

https://github.com/samccone/dogesay/blob/master/presentors/doge.coffee#L22

Any particular reasoning for this?

**Comment by jescalan** [comment]
![](http://dogesay.com/i/can/say/multiple/things.jpg)

The slice just cuts the domain root I think

**Comment by nathanharper** [comment]
yup, I'm an idjit. for some reason I thought that meant make a slice of length 1. closing!
